### PR TITLE
Remove finalizers from secret when reference is removed

### LINKED ISSUE #52: Finalizer is not removed from secret
**What happened**:
If you remove a `secretRef` from a MR, grm will not remove its finalizer from the referenced Secret.
Therefore the secret cannot be deleted without manual intervention.

With https://github.com/gardener/gardener/pull/2210 (which creates dedicated secrets for each worker pool and references each of them in the respective MR) this will lead to a problem when g/grm is released, that the Shoot's namespace in the Seed cannot be deleted anymore, if the enduser has removed a worker pool from their Shoot (because it will contain Secrets with stale finalizers).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with 2 worker pools
2. Remove one worker pool
3. Delete the Shoot
4. Observe that the Shoot's namespace in the Seed can't be deleted (pending deletion of secret for the second worker pool's cloud config)

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by tim-ebert**
**What this PR does / why we need it**:
This PR adds a new controller for secrets, that is only responsible for adding/removing `grm`'s finalizer to/from secrets referenced by ManagedResources.
It watches ManagedResources and enqueues all secrets on a generation change, that are/were referenced by the ManagedResource. It additionally enqueues secrets with its finalizer on create and update to remove its finalizer if it missed an important update event during a downtime.

So now, grm properly removes its finalizer from secrets that are not referenced by a ManagedResource anymore.

**Which issue(s) this PR fixes**:
Fixes #52

**Special notes for your reviewer**:
Tests will fail because of changes introduced by #46, but should run green after rebasing on #53
✅ test-wise depends on #53

**Release note**:

```improvement operator
`gardener-resource-manager` now properly removes its finalizer from secrets, that are not referenced by a `ManagedResource` anymore.
```
```noteworthy operator
Please ensure, that `gardener-resource-manager` has the required permissions to also update secrets now.
```

### CODE REVIEW

File: pkg/controller/managedresources/secret_controller.go [hunk 1]
```diff
@@ -0,0 +1,122 @@
+// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```
Comment (rfranzke) [inline pkg/controller/managedresources/secret_controller.go:1]:
```suggestion
// Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```

File: pkg/controller/managedresources/secret_controller.go [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+
+// SecretSecretReconciler adds/removes finalizers to/from secrets referenced by ManagedResources.
+type SecretReconciler struct {
+	log    logr.Logger
+	class  *ClassFilter
+	client client.Client
+	ctx    context.Context
+}
+
+func (r *SecretReconciler) InjectClient(client client.Client) error {
```
Comment (rfranzke) [inline pkg/controller/managedresources/secret_controller.go:41]: doc string

File: pkg/controller/managedresources/secret_controller.go [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+	r.client = client
+	return nil
+}
+
+func (r *SecretReconciler) InjectStopChannel(stopCh <-chan struct{}) error {
```
Comment (rfranzke) [inline pkg/controller/managedresources/secret_controller.go:46]: doc string

File: pkg/mapper/to_secret.go [hunk 4]
```diff
@@ -0,0 +1,56 @@
+// Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```
Comment (rfranzke) [inline pkg/mapper/to_secret.go:1]:
```suggestion
// Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```

File: pkg/predicate/has_finalizer.go [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+		},
+		UpdateFunc: func(e event.UpdateEvent) bool {
+			// We only need to check MetaNew. If the finalizer was in MetaOld and is not in MetaNew, it is already
+			// removed and we don't need to reconcile the secret.
+			if e.MetaNew == nil {
+				log.Error(nil, "Update event has no new object meta", "event", e)
+				return false
+			}
+
+			return sets.NewString(e.MetaNew.GetFinalizers()...).Has(finalizer)
```
Comment (rfranzke) [inline pkg/predicate/has_finalizer.go:49]: Can this be put into a separate function that you can call in both `CreateFunc` and `UpdateFunc`?

**Comment by gardener-botmanager** [comment]
Command "/  Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file" either unknown, wrongly parameterized or not permitted for issue/PR.

**Comment by gardener-botmanager** [comment]
Command "/  Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file" either unknown, wrongly parameterized or not permitted for issue/PR.

**Comment by tim-ebert** [comment]
@vlerenc ^^

File: pkg/predicate/has_finalizer.go [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+			// If the secret is already deleted, all finalizers are already gone and we don't need to reconcile it.
+			return false
+		},
+		GenericFunc: func(e event.GenericEvent) bool {
+			return false
+		},
+	}
+}
+
+func metaHasFinalizer(meta metav1.Object, finalizer string) bool {
```
Comment (rfranzke) [inline pkg/predicate/has_finalizer.go:62]: Hm okay, I was more thinking about also including the

```golang
	if e.MetaNew == nil {
		log.Error(nil, "Update event has no new object meta", "event", e)
		return false
	}
```

part in this function. But anyways, it's fine and doesn't matter too much.

/lgtm

Comment (tim-ebert) [reply pkg/predicate/has_finalizer.go:62]: Oh sorry, then I misunderstood. 
Anyways, let's keep it this way, so we can have more meaningful logs in case of errors (like "Create/Update event" and also the `event` attribute) without passing basically everything to the helper function :)

File: pkg/controller/managedresources/secret_controller.go [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+				secretFinalizers.Insert(controllerFinalizer)
+			} else if removeFinalizer {
+				secretFinalizers.Delete(controllerFinalizer)
+			}
+			secret.Finalizers = secretFinalizers.UnsortedList()
+			return nil
+		}); client.IgnoreNotFound(err) != nil {
+			r.log.Error(err, "failed to update finalizers of secret")
+			// dont' run into exponential backoff for adding/removing finalizers
+			return reconcile.Result{RequeueAfter: 5 * time.Second}, err
```
Comment (ialidzhikov) [inline pkg/controller/managedresources/secret_controller.go:119]: I think when err is non-nil, the RequeueAfter is ignored. Ref https://github.com/kubernetes-sigs/controller-runtime/blob/198197fe0fd7553cadd8afcd3338f8ee4b8a7e3f/pkg/internal/controller/controller.go#L256-L275

Comment (tim-ebert) [reply pkg/controller/managedresources/secret_controller.go:119]: You're right, good catch. Thanks for fixing!
